### PR TITLE
qlf_4kn8: add lib data

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

This PR moves lib data from `symbiflow-arch-defs` to this repository, which holds all device data already. This is a more suitable place for this data.

### CODE REVIEW

**Comment by sharmaln** [comment]
I think moving this data to this plugin is fine.

**Review by sharmaln — APPROVED** [review]
looks fine

**Comment by kkumar23** [comment]
@acomodi  : are you planning to remove from here ? https://github.com/QuickLogic-Corp/symbiflow-arch-defs/tree/master/quicklogic/qlf_k4n8/devices/umc22

**Comment by acomodi** [comment]
@kkumar23 Yes, I have removed that already in the upstream repository, and I am planning to adapt `symbiflow-arch-defs` to use data stored in here as soon as all the other pending upstreaming PRs are merged.

**Comment by kkumar23** [comment]
Ok. So the latest changes you are planning to merge to quicklogic/symbiflow-arch-defs ? Because we are using this repo for the release purpose.  
Again please note the toolchain wrappers depend on these lib files to generate the .lib file. So changes need to be done there as well.

**Comment by acomodi** [comment]
I am planning to use this directly upstream and than re-align the current `quicklogic/symbiflow-arch-defs` to `symbiflow/symbiflow-arch-defs` once all the relevant pieces are upstreamed. This PR is not currently modifying pre-existing data, so the flow from `quicklogic/symbiflow-arch-defs` is not affected by this change.

**Pull request merged**
