### PR TITLE
Updated VPR architecture with CLB pin equivalence enabled

### PR DESCRIPTION
**Pull request by mkurc-ant**
Contains data for VPR generated using https://github.com/QuickLogic-Corp/OpenFPGA-QLF_K4N8/pull/209

### CODE REVIEW

**Comment by mkurc-ant** [comment]
@tpagarani I generated the arch from the `main_arch_dev` branch and I can see that `dffsr` and `dffnsr` got removed. Is that correct ?

**Comment by tpagarani** [comment]
> @tpagarani I generated the arch from the `main_arch_dev` branch and I can see that `dffsr` and `dffnsr` got removed. Is that correct ?

@mkurc-ant, i think my dffsr PR never got into main_arch_dev. I just raised the PR. After I merge, can you rebase and update your PR?

**Comment by tpagarani** [comment]
> > @tpagarani I generated the arch from the `main_arch_dev` branch and I can see that `dffsr` and `dffnsr` got removed. Is that correct ?
> 
> @mkurc-ant, i think my dffsr PR never got into main_arch_dev. I just raised the PR. After I merge, can you rebase and update your PR?

That brings up another point that, we need to figure out a way to generate an automatic PR from OpenFPGA repo to qlfpga-symbiflow-plugin instead of doing it manually all the time.

**Comment by mkurc-ant** [comment]
@tpagarani Ok, I'll rebase once it lands. I've been thinking of automatizing pushing data to qlfpga-symbiflow-plugin but I don't have any clear idea how to do that at the moment.

**Comment by tpagarani** [comment]
> @tpagarani Ok, I'll rebase once it lands. I've been thinking of automatizing pushing data to qlfpga-symbiflow-plugin but I don't have any clear idea how to do that at the moment.

@mkurc-ant My PR is merged. You can rebase and update your PR.

**Comment by mkurc-ant** [comment]
@tpagarani Thanks, I've re-generated all the files and updated this PR

**Comment by tpagarani** [comment]
LGTM

**Pull request merged**
